package com.proyectox.model;
// Generated 17/11/2016 16:39:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idcat;
     private String descat;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Categoria() {
    }

	
    public Categoria(String descat) {
        this.descat = descat;
    }
    public Categoria(String descat, Set<Producto> productos) {
       this.descat = descat;
       this.productos = productos;
    }
   
    public Integer getIdcat() {
        return this.idcat;
    }
    
    public void setIdcat(Integer idcat) {
        this.idcat = idcat;
    }
    public String getDescat() {
        return this.descat;
    }
    
    public void setDescat(String descat) {
        this.descat = descat;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


