package com.proyectox.model;
// Generated 11/11/2016 20:03:18 by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer gruCodigo;
     private String gruNombre;
     private String gruId;

    public Grupo() {
    }

    public Grupo(String gruNombre, String gruId) {
       this.gruNombre = gruNombre;
       this.gruId = gruId;
    }
   
    public Integer getGruCodigo() {
        return this.gruCodigo;
    }
    
    public void setGruCodigo(Integer gruCodigo) {
        this.gruCodigo = gruCodigo;
    }
    public String getGruNombre() {
        return this.gruNombre;
    }
    
    public void setGruNombre(String gruNombre) {
        this.gruNombre = gruNombre;
    }
    public String getGruId() {
        return this.gruId;
    }
    
    public void setGruId(String gruId) {
        this.gruId = gruId;
    }




}


