package com.proyectox.model;
// Generated 11/11/2016 20:03:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idprod;
     private Categoria categoria;
     private String desprod;
     private String codbarprod;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Producto() {
    }

	
    public Producto(String desprod) {
        this.desprod = desprod;
    }
    public Producto(Categoria categoria, String desprod, String codbarprod, Set<Stock> stocks) {
       this.categoria = categoria;
       this.desprod = desprod;
       this.codbarprod = codbarprod;
       this.stocks = stocks;
    }
   
    public Integer getIdprod() {
        return this.idprod;
    }
    
    public void setIdprod(Integer idprod) {
        this.idprod = idprod;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getDesprod() {
        return this.desprod;
    }
    
    public void setDesprod(String desprod) {
        this.desprod = desprod;
    }
    public String getCodbarprod() {
        return this.codbarprod;
    }
    
    public void setCodbarprod(String codbarprod) {
        this.codbarprod = codbarprod;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


