package com.proyectox.model;
// Generated 17/11/2016 16:39:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private String rolename;
     private Set<Users> userses = new HashSet<Users>(0);

    public Roles() {
    }

	
    public Roles(String rolename) {
        this.rolename = rolename;
    }
    public Roles(String rolename, Set<Users> userses) {
       this.rolename = rolename;
       this.userses = userses;
    }
   
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


