package com.proyectox.model;
// Generated 11/11/2016 20:03:18 by Hibernate Tools 4.3.1



/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer idstock;
     private Producto producto;
     private Tienda tienda;
     private Long preventast;
     private Long precomprast;
     private Integer cantst;
     private Float descuetost;
     private Integer estadost;
     private Integer cantMinst;
     private Integer idcatStk;

    public Stock() {
    }

    public Stock(Producto producto, Tienda tienda, Long preventast, Long precomprast, Integer cantst, Float descuetost, Integer estadost, Integer cantMinst, Integer idcatStk) {
       this.producto = producto;
       this.tienda = tienda;
       this.preventast = preventast;
       this.precomprast = precomprast;
       this.cantst = cantst;
       this.descuetost = descuetost;
       this.estadost = estadost;
       this.cantMinst = cantMinst;
       this.idcatStk = idcatStk;
    }
   
    public Integer getIdstock() {
        return this.idstock;
    }
    
    public void setIdstock(Integer idstock) {
        this.idstock = idstock;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tienda getTienda() {
        return this.tienda;
    }
    
    public void setTienda(Tienda tienda) {
        this.tienda = tienda;
    }
    public Long getPreventast() {
        return this.preventast;
    }
    
    public void setPreventast(Long preventast) {
        this.preventast = preventast;
    }
    public Long getPrecomprast() {
        return this.precomprast;
    }
    
    public void setPrecomprast(Long precomprast) {
        this.precomprast = precomprast;
    }
    public Integer getCantst() {
        return this.cantst;
    }
    
    public void setCantst(Integer cantst) {
        this.cantst = cantst;
    }
    public Float getDescuetost() {
        return this.descuetost;
    }
    
    public void setDescuetost(Float descuetost) {
        this.descuetost = descuetost;
    }
    public Integer getEstadost() {
        return this.estadost;
    }
    
    public void setEstadost(Integer estadost) {
        this.estadost = estadost;
    }
    public Integer getCantMinst() {
        return this.cantMinst;
    }
    
    public void setCantMinst(Integer cantMinst) {
        this.cantMinst = cantMinst;
    }
    public Integer getIdcatStk() {
        return this.idcatStk;
    }
    
    public void setIdcatStk(Integer idcatStk) {
        this.idcatStk = idcatStk;
    }




}


