package com.proyectox.model;
// Generated 17/11/2016 16:39:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tienda generated by hbm2java
 */
public class Tienda  implements java.io.Serializable {


     private Integer idtienda;
     private String nomtienda;
     private String diretien;
     private String emailtienda;
     private String admintien;
     private Set<Stock> stocks = new HashSet<Stock>(0);

    public Tienda() {
    }

	
    public Tienda(String nomtienda) {
        this.nomtienda = nomtienda;
    }
    public Tienda(String nomtienda, String diretien, String emailtienda, String admintien, Set<Stock> stocks) {
       this.nomtienda = nomtienda;
       this.diretien = diretien;
       this.emailtienda = emailtienda;
       this.admintien = admintien;
       this.stocks = stocks;
    }
   
    public Integer getIdtienda() {
        return this.idtienda;
    }
    
    public void setIdtienda(Integer idtienda) {
        this.idtienda = idtienda;
    }
    public String getNomtienda() {
        return this.nomtienda;
    }
    
    public void setNomtienda(String nomtienda) {
        this.nomtienda = nomtienda;
    }
    public String getDiretien() {
        return this.diretien;
    }
    
    public void setDiretien(String diretien) {
        this.diretien = diretien;
    }
    public String getEmailtienda() {
        return this.emailtienda;
    }
    
    public void setEmailtienda(String emailtienda) {
        this.emailtienda = emailtienda;
    }
    public String getAdmintien() {
        return this.admintien;
    }
    
    public void setAdmintien(String admintien) {
        this.admintien = admintien;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }




}


